name: Check for Updates (Daily)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check-updates.outputs.has_changes }}
    steps:
      - name: Check for updates ðŸ”
        id: check-updates
        run: |
          last_run=$(curl -s "https://api.github.com/repos/${{ github.repository }}/actions/workflows/check.yml/runs?status=completed&per_page=1" | jq -r '.workflow_runs[0].created_at')
          exts_updated=$(curl -s "https://api.github.com/repos/DokiTeam/doki-exts/commits?since=$last_run" | jq '. | length')
          app_updated=$(curl -s "https://api.github.com/repos/DokiTeam/Doki/commits?since=$last_run" | jq '. | length')
          if [ "$exts_updated" -gt "0" ] || [ "$app_updated" -gt "0" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

  trigger_builds:
    needs: check
    if: needs.check.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo ðŸ§©
        uses: actions/checkout@v4
        
      - name: Trigger builds ðŸš€
        run: |
          gh workflow run build_release.yml
          gh workflow run build_legacy.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}