name: Check for Updates (Daily)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    name: ðŸŒ Check for updates
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check-updates.outputs.has_changes }}
    steps:
      - id: check-updates
        run: |
          since=$(date -u -d "24 hours ago" +"%Y-%m-%dT%H:%M:%SZ")
          check_app=$(curl -s "https://api.github.com/repos/DokiTeam/Doki/commits?since=$since" | jq -r 'length')
          check_exts=$(curl -s "https://api.github.com/repos/DokiTeam/doki-exts/commits?since=$since" | jq -r 'length')
          if [ "$check_app" -gt "0" ] || [ "$check_exts" -gt "0" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

  build_release:
    name: ðŸš€ Trigger Release Build
    needs: check
    if: needs.check.outputs.should_build == 'true'
    uses: ./.github/workflows/build_release.yml
    secrets: inherit

  build_legacy:
    name: ðŸš€ Trigger Legacy Build
    needs: check
    if: needs.check.outputs.should_build == 'true'
    uses: ./.github/workflows/build_legacy.yml
    secrets: inherit
