name: Trigger Doki builds

on:
  workflow_dispatch:

jobs:
  trigger_builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo ðŸ§©
        uses: actions/checkout@v4
        
      - name: Trigger builds ðŸš€
        run: |
          gh workflow run build_release.yml
          gh workflow run build_legacy.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}