name: Trigger Doki builds

on:
  workflow_dispatch:

jobs:
  build_release:
    name: Trigger Release builds ðŸš€
    uses: ./.github/workflows/build_release.yml

  build_legacy:
    name: Trigger Legacy builds ðŸš€
    uses: ./.github/workflows/build_legacy.yml
